export const REQUEST_SOMETHING = 'REQUEST_SOMETHING'
export const RECEIVE_SOMETHING = 'RECEIVE_SOMETHING'
export const IS_RECEIVING_SOMETHING = 'IS_RECEIVING_SOMETHING'
export const ERROR_GETTING_SOMETHING = 'ERROR_GETTING_SOMETHING'

export const DASHBOARD_UNLOAD = 'DASHBOARD_UNLOAD'

// Single Project
export const SUCCESS_FETCHING_PROJECT = 'SUCCESS_FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT_CONFIG = 'SUCCESS_FETCHING_PROJECT_CONFIG'
export const PROJECT_UNLOAD = 'PROJECT_UNLOAD'

export const DASHBOARD_SHOULD_REFRESH = 'DASHBOARD_SHOULD_REFRESH'
