export const REQUEST_SOMETHING = 'REQUEST_SOMETHING'
export const RECEIVE_SOMETHING = 'RECEIVE_SOMETHING'
export const IS_RECEIVING_SOMETHING = 'IS_RECEIVING_SOMETHING'
export const ERROR_GETTING_SOMETHING = 'ERROR_GETTING_SOMETHING'

export const CREATING_PROJECT = 'CREATING_PROJECT'
export const CREATING_PROJECT_UNLOAD = 'CREATING_PROJECT_UNLOAD'
export const ERROR_CREATING_PROJECT = 'ERROR_CREATING_PROJECT'
export const SUCCESS_CREATING_PROJECT = 'SUCCESS_CREATING_PROJECT'

export const DASHBOARD_UNLOAD = 'DASHBOARD_UNLOAD'

export const SUCCESS_FETCHING_PROJECT = 'SUCCESS_FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT_CONFIG = 'SUCCESS_FETCHING_PROJECT_CONFIG'
export const PROJECT_UNLOAD = 'PROJECT_UNLOAD'
