export const REQUEST_SOMETHING = 'REQUEST_SOMETHING'
export const RECEIVE_SOMETHING = 'RECEIVE_SOMETHING'
export const IS_RECEIVING_SOMETHING = 'IS_RECEIVING_SOMETHING'
export const ERROR_GETTING_SOMETHING = 'ERROR_GETTING_SOMETHING'
