// New Project
export const CREATING_PROJECT = 'CREATING_PROJECT'
export const ERROR_CREATING_PROJECT = 'ERROR_CREATING_PROJECT'
export const SUCCESS_CREATING_PROJECT = 'SUCCESS_CREATING_PROJECT'
export const CREATE_ANOTHER_PROJECT = 'CREATE_ANOTHER_PROJECT'

// Delete projects
export const DELETING_PROJECT = 'DELETING_PROJECT'
export const ERROR_DELETING_PROJECT = 'ERROR_DELETING_PROJECT'
export const SUCCESS_DELETING_PROJECT = 'SUCCESS_DELETING_PROJECT'

// Unload
export const CREATING_PROJECT_UNLOAD = 'CREATING_PROJECT_UNLOAD'
