// All projects
export const FETCHING_ALL_PROJECTS = 'FETCHING_ALL_PROJECTS'
export const SUCCESS_FETCHING_ALL_PROJECTS = 'SUCCESS_FETCHING_ALL_PROJECTS'
export const ERROR_FETCHING_ALL_PROJECTS = 'ERROR_FETCHING_ALL_PROJECTS'

// Single Project
export const FETCHING_PROJECT = 'FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT = 'SUCCESS_FETCHING_PROJECT'
export const ERROR_FETCHING_PROJECT = 'ERROR_FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT_CONFIG = 'SUCCESS_FETCHING_PROJECT_CONFIG'
export const ERROR_FETCHING_PROJECT_CONFIG = 'ERROR_FETCHING_PROJECT_CONFIG'

// New Project
export const CREATING_PROJECT = 'CREATING_PROJECT'
export const ERROR_CREATING_PROJECT = 'ERROR_CREATING_PROJECT'
export const SUCCESS_CREATING_PROJECT = 'SUCCESS_CREATING_PROJECT'

// Delete project
export const DELETING_PROJECT = 'DELETING_PROJECT'
export const ERROR_DELETING_PROJECT = 'ERROR_DELETING_PROJECT'
export const SUCCESS_DELETING_PROJECT = 'SUCCESS_DELETING_PROJECT'

// Unload
export const PROJECTS_UNLOAD = 'PROJECTS_UNLOAD'

// Updated
export const PROJECTS_UPDATED = 'PROJECTS_UPDATED'
