// New Project
export const CREATING_PROJECT = 'CREATING_PROJECT'
export const ERROR_CREATING_PROJECT = 'ERROR_CREATING_PROJECT'
export const SUCCESS_CREATING_PROJECT = 'SUCCESS_CREATING_PROJECT'
export const CREATE_ANOTHER_PROJECT = 'CREATE_ANOTHER_PROJECT'

// Unload
export const CREATING_PROJECT_UNLOAD = 'CREATING_PROJECT_UNLOAD'
