export const AUTHENTICATED = 'authenticated_user'
export const UNAUTHENTICATED = 'unauthenticated_user'
export const LOG_IN_ERROR = 'log_in_error'
export const LOG_IN_SUCCESS = 'log_in_success'
export const LOG_IN_UNLOAD = 'log_in_unload'
export const SIGN_UP_UNLOAD = 'sign_up_unload'
export const SIGN_UP_ERROR = 'signup_error'
