export const FETCHING_ACCOUNT = 'FETCHING_ACCOUNT'
export const SUCCESS_FETCHING_ACCOUNT = 'SUCCESS_FETCHING_ACCOUNT'
export const ERROR_FETCHING_ACCOUNT = 'ERROR_FETCHING_ACCOUNT'

export const UPDATING_ACCOUNT = 'UPDATING_ACCOUNT'
export const SUCCESS_UPDATING_ACCOUNT = 'SUCCESS_UPDATING_ACCOUNT'
export const ERROR_UPDATING_ACCOUNT = 'ERROR_UPDATING_ACCOUNT'

export const UPDATING_PASSWORD = 'UPDATING_PASSWORD'
export const SUCCESS_UPDATING_PASSWORD = 'SUCCESS_UPDATING_PASSWORD'
export const ERROR_UPDATING_PASSWORD = 'ERROR_UPDATING_PASSWORD'

export const ACCOUNT_UNLOAD = 'ACCOUNT_UNLOAD'
